---
# tasks file for roles/lamp
#
- name: Instalo paquetes
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Inicio servicios
  service: 
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ services }}"

- name: Agrego index.html
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: apache
    group: apache
    mode: 0644

- name: Abro puertos en firewall
  firewalld:
    zone: internal
    service: http
    state: enabled
    permanent: yes
    immediate: yes
